### PR TITLE
Updated documentation, marzipan edition

### PR DESCRIPTION
**Pull request by markseuffert**
I did a quick review/update of the documentation. Hope you like it.

### CODE REVIEW

**Comment by markseuffert** [comment]
Can you have a look please, thank you for reviewing.

**Comment by GiovanniSalmeri** [comment]
All is perfect, thank you very much indeed! I have had doubt about `asciimath2tex` (the original is in Javascript, here it is translated in PHP), but I think that it is nevertheless correct to write that yellow-math *uses* it.

**Comment by markseuffert** [comment]
I struggled with the right wording, but then I thought the important part is to say "thank you".

**Comment by markseuffert** [comment]
As an alternative I considered `This extension includes a port of the original asciimath2tex`, would this be better?

**Comment by markseuffert** [comment]
After brainstorming with @schulle4u on Discord, we considered these alternatives:

- `This extension is based on the original asciimath2tex by Christian`
- `This extension includes a port of the original asciimath2tex by Christian`
- `This extension uses a port of the original asciimath2tex by Christian`
- `This extension uses a rewrite of the original asciimath2tex by Christian`

Would you like one of these sentences?

**Comment by GiovanniSalmeri** [comment]
Sorry for causing so many language problems! I agree that the important thing is to say "thank you", so any formulation is fine (also the one currently used). But among these four wordings, probably the second and the third one seem to me the clearest. I leave you the choice! Thank you again 😊

**Comment by markseuffert** [comment]
I don't have a strong opinion and let the developer in charge have the final say. :smile:

**Pull request merged**
